name: Workshopbyzcl

on:
  push:
    branches: "v[0-9]+.[0-9]"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
 
      - name: Install Railway
        run: npm i -g @railway/cli
        
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.REPOTOKEN }}
          tag: v

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.deploytoken }}
      
      - name: notify
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA55 CI/CD Assignment Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:*\nZhang Cailei"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:*\nA0265072H"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Email:*\n<gmail.com|zcl7355608@gmail.com>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repositary:*\n<git://github.com/Zzzdaydayup/caworkshop.git>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment:*\n<https://caworkshop-production.up.railway.app>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://caworkshop-production.up.railway.app|Open Application>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TESTWEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
