name : test

on:
  push:
  branches: "v[0-9]+.[0-9]"  

jobs:
  build:
     runs-on: ubuntu-latest
    
    steps:
    - name: Chechout
      uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.repotoken }}
    - name: use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
      run: railway up
