name : test

on:
  push:
  branches: "v[0-9]+.[0-9]"  

jobs:
  build:
     runs-on: ubuntu-latest
    
    steps:
    - name: Chechout
      uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        token:$
