name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
 
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.deploytoken }}
      
      - name: notify
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
    # The following message update step does not accept a channel name.
    # Setting a channel ID here for consistency is highly recommended.
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                 }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TESTWEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
